### PR TITLE
Evaluate model on Zorro or BLiMP

### PR DESCRIPTION
**Pull request by codebyzeb**
Adjusted evaluation script from UnMasked library to allow testing a locally saved model on the Zorro or BLiMP test suite.

Todo:

- [ ] Automatically evaluate on Zorro during training
- [ ] Save detailed evaluation statistics rather than just outputting an average

### CODE REVIEW

**Review by rdiehlmartinez — COMMENTED** [review]
just FYI these types of commits can be avoided by just rebasing onto the latest commit of the branch (once you pull and fetch the latest changes from upstream)

**Review by rdiehlmartinez — COMMENTED** [review]
looks good to me - can we just move src/evaluate.py to the root dir so that we have our train and evaluate entry points in the same dir.

**Review by rdiehlmartinez — COMMENTED** [review]
could be rebased

**Review by hmcgovern — COMMENTED** [review]
```python src/evaluate.py --model_repo 'phueb/BabyBERTa-1'``` runs successfully, as do all combinations of the other command line arguments (```test_suite_name```, ```lower_case```, and ```scoring_method```). The final commit fixes stylistic things -- adding explicit type casting, argument parsing, removing duplicate code

**Pull request merged**
